version: '2'

services:
  namenode:
    image: uhopper/hadoop-namenode
    container_name: namenode
    hostname: namenode
    networks:
      - hadoop
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: uh-cluster
      constraint:node=: onet1
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    container_name: resourcemanager    
    hostname: resourcemanager
    depends_on:
      - namenode
    networks:
      - hadoop
    environment:
      constraint:node=: onet2 
    env_file:
      - ./hadoop.env

  historyserver:
    image: uhopper/hadoop-historyserver
    container_name: historyserver    
    hostname: historyserver
    depends_on:
      - namenode
    networks:
      - hadoop
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      constraint:node=: onet2
    env_file:
      - ./hadoop.env

  spark:
    image: uhopper/hadoop-spark
    container_name: spark
    hostname: spark
    networks:
      - hadoop
      - kafka
    environment:
      - SPARK_CONF_spark_eventLog_enabled=true
      - SPARK_CONF_spark_eventLog_dir=hdfs://namenode.hadoop:8020/spark-logs
      - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode.hadoop:8020/spark-logs
    env_file:
      - ./hadoop.env
    command: historyserver

  nodemanager1:
    image: uhopper/hadoop-nodemanager
    container_name: nodemanager1
    hostname: nodemanager1
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop
      - kafka
    environment:
      constraint:node=: onet1       
    env_file:
      - ./hadoop.env

  nodemanager2:
    image: uhopper/hadoop-nodemanager
    container_name: nodemanager2
    hostname: nodemanager2
    depends_on:
      - namenode
      - resourcemanager    
    networks:
      - hadoop
      - kafka
    environment:
      constraint:node=: onet2
    env_file:
      - ./hadoop.env
      
  datanode1:
    image: uhopper/hadoop-datanode
    container_name: datanode1    
    hostname: datanode1
    depends_on:
      - namenode
    networks:
      - hadoop
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      constraint:node=: onet1      
    env_file:
      - ./hadoop.env

  datanode2:
    image: uhopper/hadoop-datanode
    container_name: datanode2    
    hostname: datanode2
    depends_on:
      - namenode    
    networks:
      - hadoop
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      constraint:node=: onet2
    env_file:
      - ./hadoop.env
    
networks:
  kafka:
    external: true
  hadoop:
    external: true

volumes:
  hadoop_namenode:
    external: true
    
  hadoop_datanode1:
    external: true
    
  hadoop_datanode2:
    external: true
    
  hadoop_historyserver:
    external: true